# Wazuh App Copyright (C) 2017, Wazuh Inc. (License GPLv2)
services:
  wazuh.manager:
    image: wazuh/wazuh-manager:4.14.7
    hostname: wazuh.manager
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL="https://wazuh.indexer:9200"
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=${INDEXER_PASSWORD}
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
      - API_USERNAME=wazuh-wui
      - API_PASSWORD=${WAZUH_API_PASSWORD}
    volumes:
      - wazuh_api_configuration:/var/ossec/api/configuration
      - wazuh_etc:/var/ossec/etc
      - wazuh_logs:/var/ossec/logs
      - wazuh_queue:/var/ossec/queue
      - wazuh_var_multigroups:/var/ossec/var/multigroups
      - wazuh_integrations:/var/ossec/integrations
      - wazuh_active_response:/var/ossec/active-response/bin
      - wazuh_agentless:/var/ossec/agentless
      - wazuh_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat
      - ./config/wazuh_indexer_ssl_certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.manager.pem:/etc/ssl/filebeat.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.manager-key.pem:/etc/ssl/filebeat.key
      - ./config/wazuh_cluster/wazuh_manager.conf:/wazuh-config-mount/etc/ossec.conf

  wazuh.indexer:
    image: wazuh/wazuh-indexer:4.14.7
    hostname: wazuh.indexer
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer
      - ./config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-indexer/config/certs/root-ca.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.indexer-key.pem:/usr/share/wazuh-indexer/config/certs/wazuh.indexer.key
      - ./config/wazuh_indexer_ssl_certs/wazuh.indexer.pem:/usr/share/wazuh-indexer/config/certs/wazuh.indexer.pem
      - ./config/wazuh_indexer_ssl_certs/admin.pem:/usr/share/wazuh-indexer/config/certs/admin.pem
      - ./config/wazuh_indexer_ssl_certs/admin-key.pem:/usr/share/wazuh-indexer/config/certs/admin-key.pem
      - ./config/wazuh_indexer/wazuh.indexer.yml:/usr/share/wazuh-indexer/config/opensearch.yml
      - ./config/wazuh_indexer/internal_users.yml:/usr/share/wazuh-indexer/config/opensearch-security/internal_users.yml

  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.14.7
    hostname: wazuh.dashboard
    restart: always
    ports:
      - 443:5601
    environment:
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=${INDEXER_PASSWORD}
      - WAZUH_API_URL=https://wazuh.manager
      - DASHBOARD_USERNAME=kibanaserver
      - DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}
      - API_USERNAME=wazuh-wui
      - API_PASSWORD=${WAZUH_API_PASSWORD}
    volumes:
      - ./config/wazuh_indexer_ssl_certs/wazuh.dashboard.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.dashboard-key.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem
      - ./config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-dashboard/certs/root-ca.pem
      - ./config/wazuh_dashboard/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
      - ./config/wazuh_dashboard/wazuh.yml:/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
      - wazuh-dashboard-config:/usr/share/wazuh-dashboard/data/wazuh/config
      - wazuh-dashboard-custom:/usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom
    depends_on:
      - wazuh.indexer
    links:
      - wazuh.indexer:wazuh.indexer
      - wazuh.manager:wazuh.manager

  postgres:
    image: postgres:16-alpine
    hostname: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=soc_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  mail:
    image: ${REGISTRY_MIRROR_URL:-}ghcr.io/egos-tech/smtp:1.1.3
    restart: always
    environment:
      - "SES_USER=${SES_USER}"
      - "SES_PASSWORD=${SES_PASSWORD}"
      - "SES_REGION=${SES_REGION}"
      - "SES_PORT=${SES_PORT}"
      - "SMARTHOST_ADDRESS=${SMARTHOST_ADDRESS}"
      - "SMARTHOST_PORT=${SMARTHOST_PORT}"
      - "SMARTHOST_USER=${SMARTHOST_USER}"
      - "SMARTHOST_PASSWORD=${SMARTHOST_PASSWORD}"
      - "SMARTHOST_ALIASES=${SMARTHOST_ALIASES}"
      - "TZ=${TZ:-UTC}"

  redis:
    image: ${REGISTRY_MIRROR_URL:-}valkey/valkey:7.2
    restart: always
    command: |
      sh -c '
        if [ "$${DISABLE_REDIS_SNAPSHOT}" = "true" ] ; then
            redis_snapshot="--save \"\""
        else
            redis_snapshot=""
        fi
        if [ "$${ENABLE_REDIS_EMPTY_PASSWORD:-false}" = "true" ]; then
          exec valkey-server $${redis_snapshot}
        else
          exec valkey-server --requirepass "$${REDIS_PASSWORD}" $${redis_snapshot}
        fi
      '
    environment:
      - "ENABLE_REDIS_EMPTY_PASSWORD=${ENABLE_REDIS_EMPTY_PASSWORD:-false}"
      - "REDIS_PASSWORD=${REDIS_PASSWORD}"
      - "TZ=${TZ:-UTC}"
      - "DISABLE_REDIS_SNAPSHOT=${DISABLE_REDIS_SNAPSHOT:-false}"
    healthcheck:
      test: |
        sh -c '
          if [ "$${ENABLE_REDIS_EMPTY_PASSWORD:-false}" = "true" ]; then
            valkey-cli -p $${REDIS_PORT:-6379} ping | grep -q PONG || exit 1
          else
            valkey-cli -a "$${REDIS_PASSWORD}" -p $${REDIS_PORT:-6379} ping | grep -q PONG || exit 1
          fi
        '
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 5s
      start_interval: 5s
    volumes:
      - misp_cache_data:/data:Z

  misp-db:
    image: ${REGISTRY_MIRROR_URL:-}mariadb:10.11
    restart: always
    environment:
      - "MYSQL_USER=${MYSQL_USER:-misp}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE:-misp}"
      - "TZ=${TZ:-UTC}"
    command: "\
      --innodb-buffer-pool-size=${INNODB_BUFFER_POOL_SIZE:-2048M} \
      --innodb-change-buffering=${INNODB_CHANGE_BUFFERING:-none} \
      --innodb-io-capacity=${INNODB_IO_CAPACITY:-1000} \
      --innodb-io-capacity-max=${INNODB_IO_CAPACITY_MAX:-2000} \
      --innodb-log-file-size=${INNODB_LOG_FILE_SIZE:-600M} \
      --innodb-read-io-threads=${INNODB_READ_IO_THREADS:-16} \
      --innodb-stats-persistent=${INNODB_STATS_PERSISTENT:-ON} \
      --innodb-write-io-threads=${INNODB_WRITE_IO_THREADS:-4}"
    volumes:
      - misp_mysql_data:/var/lib/mysql:Z
    cap_add:
      - SYS_NICE
    healthcheck:
      test: mysqladmin --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD status
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 30s
      start_interval: 5s

  misp-core:
    image: ${REGISTRY_MIRROR_URL:-}ghcr.io/misp/misp-docker/misp-core:${CORE_RUNNING_TAG:-latest}
    restart: always
    depends_on:
      redis:
        condition: service_healthy
      misp-db:
        condition: service_healthy
      misp-modules:
        condition: service_healthy
    healthcheck:
      test: bash -c 'echo > /dev/tcp/127.0.0.1/9002' || exit 1
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 60s
      start_interval: 5s
    expose:
      - 9002
    volumes:
      - "./config/misp/configs/:/var/www/MISP/app/Config/:Z"
      - "./config/misp/logs/:/var/www/MISP/app/tmp/logs/:Z"
      - "./config/misp/files/:/var/www/MISP/app/files/:Z"
      - "./config/misp/gnupg/:/var/www/MISP/.gnupg/:Z"
      - "misp_guard_ca:/usr/local/share/ca-certificates/misp_guard:Z"
    cap_add:
      - AUDIT_WRITE
    environment:
      - "BASE_URL=${BASE_URL:?Missing BASE_URL in .env}"
      - "CRON_USER_ID=${CRON_USER_ID}"
      - "CRON_PULLALL=${CRON_PULLALL}"
      - "CRON_PUSHALL=${CRON_PUSHALL}"
      - "FETCH_FEED_INTERVAL=${FETCH_FEED_INTERVAL}"
      - "CACHE_FEED_INTERVAL=${CACHE_FEED_INTERVAL}"
      - "DISABLE_IPV6=${DISABLE_IPV6}"
      - "ENABLE_DB_SETTINGS=${ENABLE_DB_SETTINGS}"
      - "AUTH_ENFORCED=${AUTH_ENFORCED}"
      - "ENABLE_BACKGROUND_UPDATES=${ENABLE_BACKGROUND_UPDATES}"
      - "ENCRYPTION_KEY=${ENCRYPTION_KEY}"
      - "SALT=${SALT}"
      - "UUID=${UUID}"
      - "DISABLE_CA_REFRESH=${DISABLE_CA_REFRESH}"
      - "DISABLE_PRINTING_PLAINTEXT_CREDENTIALS=${DISABLE_PRINTING_PLAINTEXT_CREDENTIALS}"
      - "ADMIN_EMAIL=${ADMIN_EMAIL}"
      - "MISP_CONTACT=${MISP_CONTACT}"
      - "MISP_EMAIL=${MISP_EMAIL}"
      - "ADMIN_PASSWORD=${ADMIN_PASSWORD}"
      - "ADMIN_KEY=${ADMIN_KEY}"
      - "ADMIN_ORG=${ADMIN_ORG}"
      - "ADMIN_ORG_UUID=${ADMIN_ORG_UUID}"
      - "GPG_PASSPHRASE=${GPG_PASSPHRASE}"
      - "ATTACHMENTS_DIR=${ATTACHMENTS_DIR}"
      - "TZ=${TZ:-UTC}"
      - "ENABLE_THEMES=${ENABLE_THEMES}"
      - "PROXY_ENABLE=${PROXY_ENABLE}"
      - "PROXY_HOST=${PROXY_HOST}"
      - "PROXY_PORT=${PROXY_PORT}"
      - "PROXY_METHOD=${PROXY_METHOD}"
      - "PROXY_USER=${PROXY_USER}"
      - "PROXY_PASSWORD=${PROXY_PASSWORD}"
      - "STUNNEL=${STUNNEL}"
      - "STUNNEL_CONFIG=${STUNNEL_CONFIG}"
      - "SUPERVISOR_HOST=${SUPERVISOR_HOST:-127.0.0.1}"
      - "SUPERVISOR_USERNAME=${SUPERVISOR_USERNAME:-supervisor}"
      - "SUPERVISOR_PASSWORD=${SUPERVISOR_PASSWORD}"
      - "MYSQL_HOST=${MYSQL_HOST:-misp-db}"
      - "MYSQL_PORT=${MYSQL_PORT:-3306}"
      - "MYSQL_USER=${MYSQL_USER:-misp}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE:-misp}"
      - "MYSQL_TLS=${MYSQL_TLS:-false}"
      - "REDIS_HOST=${REDIS_HOST:-redis}"
      - "REDIS_PORT=${REDIS_PORT:-6379}"
      - "REDIS_PASSWORD=${REDIS_PASSWORD}"
      - "ENABLE_REDIS_EMPTY_PASSWORD=${ENABLE_REDIS_EMPTY_PASSWORD:-false}"
      - "DEBUG=${DEBUG}"
      - "SMTP_FQDN=${SMTP_FQDN}"
      - "SMTP_PORT=${SMTP_PORT:-25}"
      - "FASTCGI_LISTEN_STATUS=${FASTCGI_LISTEN_STATUS:-misp-core:9003}"
      - "PHP_LISTEN_FPM=${PHP_LISTEN_FPM:-true}"
      - "PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-2048M}"
      - "PHP_MAX_EXECUTION_TIME=${PHP_MAX_EXECUTION_TIME:-300}"
      - "PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE:-50M}"
      - "PHP_POST_MAX_SIZE=${PHP_POST_MAX_SIZE:-50M}"
      - "PHP_MAX_INPUT_TIME=${PHP_MAX_INPUT_TIME:-300}"
      - "PHP_MAX_FILE_UPLOADS=${PHP_MAX_FILE_UPLOADS:-50}"
      - "PHP_FCGI_CHILDREN=${PHP_FCGI_CHILDREN:-5}"
      - "PHP_FCGI_START_SERVERS=${PHP_FCGI_START_SERVERS:-2}"
      - "PHP_FCGI_SPARE_SERVERS=${PHP_FCGI_SPARE_SERVERS:-1}"
      - "PHP_FCGI_MAX_REQUESTS=${PHP_FCGI_MAX_REQUESTS:-0}"
      - "PHP_SESSION_TIMEOUT=${PHP_SESSION_TIMEOUT:-60}"
      - "PHP_SESSION_COOKIE_TIMEOUT=${PHP_SESSION_COOKIE_TIMEOUT:-10080}"
      - "PHP_SESSION_DEFAULTS=${PHP_SESSION_DEFAULTS:-php}"
      - "PHP_SESSION_AUTO_REGENERATE=${PHP_SESSION_AUTO_REGENERATE:-false}"
      - "PHP_SESSION_CHECK_AGENT=${PHP_SESSION_CHECK_AGENT:-false}"
      - "PHP_SESSION_COOKIE_SECURE=${PHP_SESSION_COOKIE_SECURE:-true}"
      - "PHP_SESSION_COOKIE_DOMAIN=${PHP_SESSION_COOKIE_DOMAIN}"
      - "PHP_SESSION_COOKIE_SAMESITE=${PHP_SESSION_COOKIE_SAMESITE:-Lax}"

  misp-nginx:
    image: ${REGISTRY_MIRROR_URL:-}ghcr.io/misp/misp-docker/misp-nginx:${CORE_RUNNING_TAG:-latest}
    restart: always
    depends_on:
      misp-core:
        condition: service_healthy
    ports:
      - "${NGINX_HTTP_PORT:-80}:8080"
      - "${NGINX_HTTPS_PORT:-8443}:8443"
    volumes:
      - "./config/misp/ssl:/etc/nginx/certs:ro,Z"
    tmpfs:
      - /etc/nginx/conf.d:mode=0755,uid=101,gid=101
      - /var/cache/nginx:mode=0755,uid=101,gid=101
      - /tmp:mode=1777
    user: nginx
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      - "TZ=${TZ}"
      - "BASE_URL=${BASE_URL:?Missing BASE_URL in .env}"
      - "DISABLE_IPV6=${DISABLE_IPV6}"
      - "NGINX_X_FORWARDED_FOR=${NGINX_X_FORWARDED_FOR}"
      - "NGINX_SET_REAL_IP_FROM=${NGINX_SET_REAL_IP_FROM}"
      - "NGINX_CLIENT_MAX_BODY_SIZE=${NGINX_CLIENT_MAX_BODY_SIZE:-50M}"
      - "FASTCGI_LISTEN=${FASTCGI_LISTEN:-misp-core:9002}"
      - "FASTCGI_LISTEN_STATUS=${FASTCGI_LISTEN_STATUS:-misp-core:9003}"
      - "FASTCGI_READ_TIMEOUT=${FASTCGI_READ_TIMEOUT:-300s}"
      - "FASTCGI_SEND_TIMEOUT=${FASTCGI_SEND_TIMEOUT:-300s}"
      - "FASTCGI_CONNECT_TIMEOUT=${FASTCGI_CONNECT_TIMEOUT:-300s}"
      - "NGINX_HSTS_MAX_AGE=${NGINX_HSTS_MAX_AGE}"
      - "NGINX_X_FRAME_OPTIONS=${NGINX_X_FRAME_OPTIONS}"
      - "NGINX_CONTENT_SECURITY_POLICY=${NGINX_CONTENT_SECURITY_POLICY}"

  misp-modules:
    image: ${REGISTRY_MIRROR_URL:-}ghcr.io/misp/misp-docker/misp-modules:${MODULES_RUNNING_TAG:-latest}
    restart: always
    healthcheck:
      test: "/bin/bash -c '</dev/tcp/localhost/6666'"
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 5s
      start_interval: 5s
    volumes:
      - "./config/misp/custom/action_mod/:/custom/action_mod/:Z"
      - "./config/misp/custom/expansion/:/custom/expansion/:Z"
      - "./config/misp/custom/export_mod/:/custom/export_mod/:Z"
      - "./config/misp/custom/import_mod/:/custom/import_mod/:Z"
    environment:
      - "TZ=${TZ:-UTC}"

  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - "TZ=${TZ:-UTC}"
      - "N8N_SECURE_COOKIE=false"
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  wazuh_api_configuration:
  wazuh_etc:
  wazuh_logs:
  wazuh_queue:
  wazuh_var_multigroups:
  wazuh_integrations:
  wazuh_active_response:
  wazuh_agentless:
  wazuh_wodles:
  filebeat_etc:
  filebeat_var:
  wazuh-indexer-data:
  wazuh-dashboard-config:
  wazuh-dashboard-custom:
  postgres_data:
  misp_mysql_data:
  misp_cache_data:
  misp_guard_ca:
  n8n_data:
